services:
  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      POSTGRES_DB: lesno
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: legopass
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lesno
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: legopass
    depends_on:
      - db
