spring.application.name=RelatedProducts

spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/lesno
spring.datasource.username=postgres
spring.datasource.password=legopass

spring.mvc.problemdetails.enabled=true

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.hibernate.format_sql=true